import{a as T,i as l,S as L}from"./assets/vendor-BDaiwwc1.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&r(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(e){if(e.ep)return;e.ep=!0;const o=i(e);fetch(e.href,o)}})();const f=document.querySelector(".loadMoreBTN");async function m(s,t,i){try{const e=(await T.get("https://pixabay.com/api/",{params:{key:"47392401-769446c280b709c486589ce4f",q:s,image_type:"photo",orientation:"horizontal",safesearch:"true",page:t,per_page:i}})).data;return f.style.pointerEvents="all",f.style.display="flex",e}catch(r){return console.error("Error fetching images:",r),l.show({position:"topRight",iconUrl:"../img/x.svg",message:"Something went wrong. Please try again later!",backgroundColor:"#EF4040",messageColor:"white"}),[]}}function h(s){const t=document.querySelector(".gallery"),i=s.map(({largeImageURL:e,webformatURL:o,tags:n,likes:y,views:w,comments:S,downloads:b})=>`
            <li class="list-item">

            <a href="${e}" >  <img class="image" src="${o}" alt="${n}"></a>
             
                <ul class="info-list">
                <li class="info-item"> <h3 class="infoTitle">Likes</h3> <p class="infoTxt">${y}</p></li>
                <li class="info-item"><h3 class="infoTitle">Views</h3> <p class="infoTxt">${w}</p></li>
                <li class="info-item"><h3 class="infoTitle">Comments</h3> <p class="infoTxt">${S}</p></li>
                <li class="info-item"><h3 class="infoTitle">Downloads</h3> <p class="infoTxt">${b}</p></li>
                </ul>
              </li>  
            `).join("");t.insertAdjacentHTML("beforeend",i),new L(".gallery a").refresh()}const x=document.querySelector(".form-input"),p=document.querySelector(".loadMoreBTN"),d=document.querySelector(".loadSpin");let c=1;const g=15;let a="",u=0;function M(s){s.preventDefault(),d.style.display="flex",c+=1,m(a,c,g).then(t=>(u-=t.hits.length,u<=0&&(p.style.display="none",l.show({message:"We're sorry, but you've reached the end of search results."})),d.style.display="none",t.hits)).then(t=>h(t)).then(()=>{window.scrollBy({top:209.19*2,behavior:"smooth"})}).catch(t=>{l.show({message:"Something went wrong"})})}function q(s){s.preventDefault(),a=s.target.elements["input-field"].value.trim();const t=document.querySelector(".loader-container"),i=document.querySelector(".gallery");if(c=1,a)t.style.display="flex",m(a,c,g).then(r=>{t.style.display="none",i.innerHTML="",u=r.totalHits,u-=r.hits.length,h(r.hits)}).catch(r=>{i.innerHTML="",l.show({message:"Something went wrong"})}).finally(()=>{s.target.reset()});else{l.show({message:"Sorry, you forgot necessery information"});return}}p.addEventListener("click",M);x.addEventListener("submit",q);
//# sourceMappingURL=index.js.map
