import{a as S,i as l,S as x}from"./assets/vendor-BDaiwwc1.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();async function d(i,t,r){try{const e=(await S.get("https://pixabay.com/api/",{params:{key:"47392401-769446c280b709c486589ce4f",q:i,image_type:"photo",orientation:"horizontal",safesearch:"true",page:t,per_page:r}})).data;return e.totalHits===0&&l.show({position:"topRight",iconUrl:"../img/x.svg",message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"#EF4040",messageColor:"white"}),e}catch{return l.show({position:"topRight",iconUrl:"../img/x.svg",message:"Something went wrong. Please try again later!",backgroundColor:"#EF4040",messageColor:"white"}),[]}}function m(i){const t=document.querySelector(".gallery"),r=i.map(({largeImageURL:e,webformatURL:o,tags:a,likes:p,views:y,comments:w,downloads:b})=>`
            <li class="list-item">

            <a href="${e}" >  <img class="image" src="${o}" alt="${a}"></a>
             
                <ul class="info-list">
                <li class="info-item"> <h3 class="infoTitle">Likes</h3> <p class="infoTxt">${p}</p></li>
                <li class="info-item"><h3 class="infoTitle">Views</h3> <p class="infoTxt">${y}</p></li>
                <li class="info-item"><h3 class="infoTitle">Comments</h3> <p class="infoTxt">${w}</p></li>
                <li class="info-item"><h3 class="infoTitle">Downloads</h3> <p class="infoTxt">${b}</p></li>
                </ul>
              </li>  
            `).join("");t.insertAdjacentHTML("beforeend",r),new x(".gallery a").refresh()}const L=document.querySelector(".form-input"),n=document.querySelector(".loadMoreBTN"),g=document.querySelector(".loadSpin");let u=1;const h=15;let c="",f=0;function T(i){i.preventDefault(),g.style.display="flex",u+=1,d(c,u,h).then(t=>(f-=t.hits.length,f<=0&&(l.show({message:"We're sorry, but you've reached the end of search results."}),n.style.display="none"),t.hits)).then(t=>{m(t)}).then(()=>{window.scrollBy({top:209.19*2,behavior:"smooth"})}).catch(t=>{l.show({message:"Something went wrong"})}).finally(()=>{g.style.display="none"})}function v(i){i.preventDefault(),c=i.target.elements["input-field"].value.trim();const t=document.querySelector(".loader-container"),r=document.querySelector(".gallery");if(u=1,c)t.style.display="flex",d(c,u,h).then(s=>{t.style.display="none",r.innerHTML="",f=s.totalHits,f-=s.hits.length,m(s.hits),s.totalHits<=h||s.hits.length===0?n.style.display="none":(n.style.pointerEvents="all",n.style.display="flex")}).catch(s=>{r.innerHTML="",l.show({message:"Something went wrong"})}).finally(()=>{i.target.reset()});else{l.show({message:"Sorry, you forgot necessary information"}),n.style.display="none";return}}n.addEventListener("click",T);L.addEventListener("submit",v);
//# sourceMappingURL=index.js.map
